language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.10.3

secure: "X0812KB22DcFQzGy8d1X1+EqkpwhiOaKNB2BX7xob2pvSI3b+YNGSqN1/N+tWH3I5QqDeJcyFTwjp67Omm1c3yhvWyrPTCM5ZQFndLusGcRdnPL5GGlcRpwDHrVei9K3yvcudnBuisbGID6x3WovGepNr72lQFTUs/2EWwEonitvuilp38X/sQn6iw2FahhC81Axj1DmPgJHJjV6vcigs6Y3DC7Hp0zYDMhbcLAu2FE457+DFih1VOdD8XP8+QkIrgoqyZqSP/h2nbs1WJuecmYf99SOQuj77SpDR4RCJ2OBcACy+HYZjQpwiIFU27ortO85cvvnvPiNy/NEHzmZtZP5Ro9YHJYLakAFZcur90mngbFTGVVoKdSAkzeOW6rpjs4z6C56mWfHmLqt/97oHx3dC2kyd4vTUP4EXDcSUrkpJFu941AtKIiJHYuKF2zUyEEp9DUdtPxhowi5ZzJkIAqVw/nnBbrEvjKmDWJv9STBl86Bbe7REIryhoPUDi51W4/rBh2yVCDHe5umoKr4yV6eVx0FOts002p35QxhRb2UGrnLSe1TgR2Kd8ANAXYPylt0b8Q3CYu/GGFSaRiLRYRWK/geL4gA5izxpjAeXHl4bofXBhsDmrcX0PeHPYhy6RoGM3wHOXHjF4Pn1WPofoi3O5F/NikmIB2oXstnlIA="
